formatter: "markdown" # this is required

version: ""

recursive:
  enabled: false
  path: modules

content: ""

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

sections:
  hide: # we remove the providers section because the actual provider used depends on the local build environment, we only document version constraints
    - providers